// Shared tensor visualization utilities — Canvas 2D, no chart libraries.
// All tensor data is Float32Array.

export type ColormapName = 'viridis' | 'coolwarm' | 'magma' | 'blueGreenRed' | 'inferno' | 'RdBu' | 'gray' | 'turbo' | 'cividis';

// ---------------------------------------------------------------------------
// Colormap LUTs — 256 entries x 3 channels (RGB), stored as Uint8Array(768).
// Generated by linearly interpolating between key color stops.
// ---------------------------------------------------------------------------

function buildLUT(stops: [number, number, number][]): Uint8Array {
	const lut = new Uint8Array(768);
	const n = stops.length - 1;
	for (let i = 0; i < 256; i++) {
		const t = i / 255;
		const segment = Math.min(Math.floor(t * n), n - 1);
		const local = t * n - segment;
		const a = stops[segment];
		const b = stops[segment + 1];
		lut[i * 3] = Math.round(a[0] + (b[0] - a[0]) * local);
		lut[i * 3 + 1] = Math.round(a[1] + (b[1] - a[1]) * local);
		lut[i * 3 + 2] = Math.round(a[2] + (b[2] - a[2]) * local);
	}
	return lut;
}

const viridisStops: [number, number, number][] = [
	[68, 1, 84],
	[72, 23, 105],
	[67, 43, 117],
	[57, 63, 121],
	[45, 82, 122],
	[37, 99, 120],
	[30, 115, 116],
	[25, 132, 109],
	[34, 148, 95],
	[64, 163, 74],
	[109, 176, 49],
	[163, 186, 30],
	[211, 193, 35],
	[248, 205, 52],
	[253, 231, 37],
];

const coolwarmStops: [number, number, number][] = [
	[59, 76, 192],
	[77, 105, 215],
	[103, 136, 234],
	[133, 165, 245],
	[163, 190, 249],
	[190, 211, 247],
	[213, 226, 239],
	[234, 234, 234],
	[239, 220, 209],
	[247, 199, 175],
	[249, 174, 142],
	[241, 144, 111],
	[227, 111, 82],
	[208, 73, 56],
	[180, 4, 38],
];

const magmaStops: [number, number, number][] = [
	[0, 0, 4],
	[11, 6, 37],
	[32, 12, 74],
	[60, 15, 101],
	[89, 17, 110],
	[117, 21, 110],
	[146, 32, 103],
	[175, 48, 89],
	[201, 71, 72],
	[222, 100, 60],
	[238, 133, 55],
	[249, 170, 63],
	[254, 210, 94],
	[254, 240, 148],
	[252, 253, 191],
];

const blueGreenRedStops: [number, number, number][] = [
	[0, 0, 255],
	[0, 64, 224],
	[0, 128, 192],
	[0, 180, 140],
	[0, 210, 80],
	[0, 230, 0],
	[80, 210, 0],
	[140, 190, 0],
	[190, 160, 0],
	[220, 120, 0],
	[240, 80, 0],
	[255, 40, 0],
	[255, 0, 0],
];

const infernoStops: [number, number, number][] = [
	[0, 0, 4],
	[12, 7, 45],
	[40, 11, 84],
	[72, 12, 104],
	[101, 18, 108],
	[132, 26, 104],
	[163, 41, 87],
	[192, 62, 63],
	[217, 89, 37],
	[236, 121, 12],
	[246, 158, 3],
	[249, 196, 22],
	[242, 234, 74],
	[252, 255, 164],
];

const RdBuStops: [number, number, number][] = [
	[103, 0, 31],
	[178, 24, 43],
	[214, 96, 77],
	[244, 165, 130],
	[253, 219, 199],
	[247, 247, 247],
	[209, 229, 240],
	[146, 197, 222],
	[67, 147, 195],
	[33, 102, 172],
	[5, 48, 97],
];

const grayStops: [number, number, number][] = [
	[0, 0, 0],
	[255, 255, 255],
];

const turboStops: [number, number, number][] = [
	[48, 18, 59],
	[70, 68, 172],
	[62, 125, 236],
	[29, 179, 247],
	[26, 222, 195],
	[79, 244, 119],
	[159, 246, 44],
	[212, 226, 25],
	[246, 189, 18],
	[253, 141, 14],
	[240, 89, 12],
	[210, 40, 12],
	[165, 8, 10],
	[122, 4, 3],
];

const cividisStops: [number, number, number][] = [
	[0, 32, 77],
	[25, 51, 92],
	[52, 69, 100],
	[76, 87, 106],
	[100, 104, 111],
	[123, 121, 113],
	[147, 138, 107],
	[171, 157, 93],
	[195, 177, 73],
	[218, 197, 47],
	[234, 221, 39],
	[253, 253, 56],
];

export const COLORMAPS: Record<ColormapName, Uint8Array> = {
	viridis: buildLUT(viridisStops),
	coolwarm: buildLUT(coolwarmStops),
	magma: buildLUT(magmaStops),
	blueGreenRed: buildLUT(blueGreenRedStops),
	inferno: buildLUT(infernoStops),
	RdBu: buildLUT(RdBuStops),
	gray: buildLUT(grayStops),
	turbo: buildLUT(turboStops),
	cividis: buildLUT(cividisStops),
};

// ---------------------------------------------------------------------------
// Spatial dimension helpers
// ---------------------------------------------------------------------------

export interface SpatialDims {
	batches: number;
	channels: number;
	height: number;
	width: number;
}

/** Map 1D-5D tensor shapes to {batches, channels, height, width}. */
export function getSpatialDims(shape: number[]): SpatialDims {
	switch (shape.length) {
		case 1:
			return { batches: 1, channels: 1, height: 1, width: shape[0] };
		case 2:
			return { batches: 1, channels: 1, height: shape[0], width: shape[1] };
		case 3:
			return { batches: 1, channels: shape[0], height: shape[1], width: shape[2] };
		case 4:
			return { batches: shape[0], channels: shape[1], height: shape[2], width: shape[3] };
		case 5:
			// Flatten extra depth dim into channels
			return {
				batches: shape[0],
				channels: shape[1] * shape[2],
				height: shape[3],
				width: shape[4],
			};
		default:
			// For higher dims, collapse all leading dims except last two into channels
			if (shape.length === 0) {
				return { batches: 1, channels: 1, height: 1, width: 1 };
			}
			const w = shape[shape.length - 1];
			const h = shape.length >= 2 ? shape[shape.length - 2] : 1;
			let ch = 1;
			for (let i = 1; i < shape.length - 2; i++) {
				ch *= shape[i];
			}
			const n = shape[0];
			return { batches: n, channels: ch, height: h, width: w };
	}
}

// ---------------------------------------------------------------------------
// Slice extraction
// ---------------------------------------------------------------------------

export interface SliceResult {
	data: Float32Array;
	h: number;
	w: number;
}

/**
 * Extract a 2D slice [h, w] from a tensor given batch and channel indices.
 * Uses subarray() for zero-copy when the slice is contiguous in memory.
 */
export function extractSlice(
	tensor: Float32Array,
	shape: number[],
	batch: number,
	channel: number,
): SliceResult {
	const dims = getSpatialDims(shape);
	const { channels, height, width } = dims;
	const sliceSize = height * width;
	const batchStride = channels * sliceSize;
	const offset = batch * batchStride + channel * sliceSize;

	return {
		data: tensor.subarray(offset, offset + sliceSize),
		h: height,
		w: width,
	};
}

// ---------------------------------------------------------------------------
// Statistics
// ---------------------------------------------------------------------------

export interface TensorStats {
	min: number;
	max: number;
	mean: number;
	std: number;
}

/** Compute min, max, mean, std of a Float32Array. Single pass for mean, second for std. */
export function computeStats(data: Float32Array): TensorStats {
	if (data.length === 0) {
		return { min: 0, max: 0, mean: 0, std: 0 };
	}

	let min = data[0];
	let max = data[0];
	let sum = 0;

	for (let i = 0; i < data.length; i++) {
		const v = data[i];
		if (v < min) min = v;
		if (v > max) max = v;
		sum += v;
	}

	const mean = sum / data.length;

	let sumSq = 0;
	for (let i = 0; i < data.length; i++) {
		const d = data[i] - mean;
		sumSq += d * d;
	}
	const std = Math.sqrt(sumSq / data.length);

	return { min, max, mean, std };
}

// ---------------------------------------------------------------------------
// Histogram
// ---------------------------------------------------------------------------

export interface HistogramResult {
	counts: Float32Array;
	edges: Float32Array;
}

/**
 * Compute histogram of data into `bins` buckets.
 * If range is not provided, auto-compute from data min/max.
 */
export function computeHistogram(
	data: Float32Array,
	bins: number,
	range?: [number, number],
): HistogramResult {
	let lo: number, hi: number;
	if (range) {
		lo = range[0];
		hi = range[1];
	} else {
		lo = data[0];
		hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
	}

	// Handle degenerate case where all values are the same
	if (hi === lo) {
		hi = lo + 1;
	}

	const counts = new Float32Array(bins);
	const edges = new Float32Array(bins + 1);
	const step = (hi - lo) / bins;

	for (let i = 0; i <= bins; i++) {
		edges[i] = lo + step * i;
	}

	const invStep = 1 / step;
	for (let i = 0; i < data.length; i++) {
		let idx = Math.floor((data[i] - lo) * invStep);
		if (idx < 0) idx = 0;
		if (idx >= bins) idx = bins - 1;
		counts[idx]++;
	}

	return { counts, edges };
}

// ---------------------------------------------------------------------------
// Colormap lookup
// ---------------------------------------------------------------------------

/**
 * Map a normalized value (0-1) to an RGB triplet using the given colormap LUT.
 * Values are clamped to [0, 1].
 */
export function colormapRGB(value: number, map: ColormapName): [number, number, number] {
	const lut = COLORMAPS[map];
	const idx = Math.max(0, Math.min(255, Math.round(value * 255)));
	const base = idx * 3;
	return [lut[base], lut[base + 1], lut[base + 2]];
}

// ---------------------------------------------------------------------------
// Value → ImageData
// ---------------------------------------------------------------------------

/**
 * Convert a Float32Array of [h * w] values into an ImageData using the given colormap.
 * If range is not provided, auto-computes from data min/max.
 */
export function valueToImageData(
	data: Float32Array,
	w: number,
	h: number,
	colormap: ColormapName,
	range?: [number, number],
): ImageData {
	let lo: number, hi: number;
	if (range) {
		lo = range[0];
		hi = range[1];
	} else {
		lo = data[0];
		hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
	}

	const span = hi - lo || 1; // avoid division by zero
	const invSpan = 1 / span;
	const lut = COLORMAPS[colormap];
	const img = new ImageData(w, h);
	const pixels = img.data; // Uint8ClampedArray

	for (let i = 0; i < data.length; i++) {
		const t = (data[i] - lo) * invSpan;
		const idx = Math.max(0, Math.min(255, Math.round(t * 255)));
		const lutBase = idx * 3;
		const pxBase = i * 4;
		pixels[pxBase] = lut[lutBase];
		pixels[pxBase + 1] = lut[lutBase + 1];
		pixels[pxBase + 2] = lut[lutBase + 2];
		pixels[pxBase + 3] = 255;
	}

	return img;
}

// ---------------------------------------------------------------------------
// Value formatting
// ---------------------------------------------------------------------------

/** Smart number formatting: exponential for tiny values, fixed(4) otherwise. */
export function formatValue(v: number): string {
	if (v === 0) return '0';
	const abs = Math.abs(v);
	if (abs < 0.0001) return v.toExponential(2);
	return v.toFixed(4);
}

// ---------------------------------------------------------------------------
// Cosine similarity
// ---------------------------------------------------------------------------

/** Compute cosine similarity between two Float32Arrays of equal length. */
export function cosineSimilarity(a: Float32Array, b: Float32Array): number {
	let dot = 0;
	let normA = 0;
	let normB = 0;

	for (let i = 0; i < a.length; i++) {
		dot += a[i] * b[i];
		normA += a[i] * a[i];
		normB += b[i] * b[i];
	}

	const denom = Math.sqrt(normA) * Math.sqrt(normB);
	if (denom === 0) return 0;
	return dot / denom;
}

// ---------------------------------------------------------------------------
// Colorbar drawing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Normalization modes
// ---------------------------------------------------------------------------

export type NormMode = 'linear' | 'log' | 'symlog' | 'percentile' | 'centered' | 'histEq' | 'gamma';

export interface NormOptions {
	mode: NormMode;
	/** Gamma exponent for 'gamma' mode (default 0.5) */
	gamma?: number;
	/** Percentile bounds for 'percentile' mode [lo, hi] (default [5, 95]) */
	percentiles?: [number, number];
	/** Linear threshold for 'symlog' mode (default 1e-3) */
	linthresh?: number;
}

/** Normalize a Float32Array to [0,1] using the specified mode. Returns a new array. */
export function normalizeData(data: Float32Array, opts: NormOptions): Float32Array {
	const out = new Float32Array(data.length);
	if (data.length === 0) return out;

	const { mode } = opts;

	if (mode === 'linear') {
		let lo = data[0], hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
		const span = hi - lo || 1;
		for (let i = 0; i < data.length; i++) out[i] = (data[i] - lo) / span;
	} else if (mode === 'log') {
		let lo = data[0], hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
		const logMax = Math.log(hi - lo + 1) || 1;
		for (let i = 0; i < data.length; i++) out[i] = Math.log(data[i] - lo + 1) / logMax;
	} else if (mode === 'symlog') {
		const lt = opts.linthresh ?? 1e-3;
		// Symmetric log: linear in [-lt, lt], log outside
		let maxAbs = 0;
		for (let i = 0; i < data.length; i++) {
			const a = Math.abs(data[i]);
			if (a > maxAbs) maxAbs = a;
		}
		const logScale = maxAbs > lt ? Math.log10(maxAbs / lt) + 1 : 1;
		for (let i = 0; i < data.length; i++) {
			const v = data[i];
			const a = Math.abs(v);
			let mapped: number;
			if (a <= lt) {
				mapped = v / lt; // [-1, 1]
			} else {
				mapped = Math.sign(v) * (Math.log10(a / lt) + 1);
			}
			out[i] = (mapped / logScale + 1) / 2; // map to [0,1]
		}
	} else if (mode === 'percentile') {
		const [pLo, pHi] = opts.percentiles ?? [5, 95];
		const sorted = Float32Array.from(data).sort();
		const lo = sorted[Math.floor(sorted.length * pLo / 100)];
		const hi = sorted[Math.ceil(sorted.length * pHi / 100) - 1];
		const span = hi - lo || 1;
		for (let i = 0; i < data.length; i++) {
			out[i] = Math.max(0, Math.min(1, (data[i] - lo) / span));
		}
	} else if (mode === 'centered') {
		// Center at 0, symmetric range
		let maxAbs = 0;
		for (let i = 0; i < data.length; i++) {
			const a = Math.abs(data[i]);
			if (a > maxAbs) maxAbs = a;
		}
		const span = maxAbs || 1;
		for (let i = 0; i < data.length; i++) out[i] = (data[i] / span + 1) / 2;
	} else if (mode === 'histEq') {
		// Histogram equalization
		const bins = 256;
		let lo = data[0], hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
		const span = hi - lo || 1;
		const hist = new Uint32Array(bins);
		for (let i = 0; i < data.length; i++) {
			const idx = Math.min(bins - 1, Math.max(0, Math.floor((data[i] - lo) / span * (bins - 1))));
			hist[idx]++;
		}
		// CDF
		const cdf = new Float32Array(bins);
		cdf[0] = hist[0];
		for (let i = 1; i < bins; i++) cdf[i] = cdf[i - 1] + hist[i];
		const cdfMin = cdf.find(v => v > 0) ?? 0;
		const cdfRange = data.length - cdfMin || 1;
		for (let i = 0; i < data.length; i++) {
			const idx = Math.min(bins - 1, Math.max(0, Math.floor((data[i] - lo) / span * (bins - 1))));
			out[i] = (cdf[idx] - cdfMin) / cdfRange;
		}
	} else if (mode === 'gamma') {
		const g = opts.gamma ?? 0.5;
		let lo = data[0], hi = data[0];
		for (let i = 1; i < data.length; i++) {
			if (data[i] < lo) lo = data[i];
			if (data[i] > hi) hi = data[i];
		}
		const span = hi - lo || 1;
		for (let i = 0; i < data.length; i++) {
			const t = (data[i] - lo) / span;
			out[i] = Math.pow(Math.max(0, Math.min(1, t)), g);
		}
	}

	return out;
}

// ---------------------------------------------------------------------------
// Normalized value → ImageData (uses pre-normalized [0,1] data)
// ---------------------------------------------------------------------------

/** Convert pre-normalized [0,1] Float32Array to ImageData. */
export function normalizedToImageData(
	data: Float32Array,
	w: number,
	h: number,
	colormap: ColormapName,
): ImageData {
	const lut = COLORMAPS[colormap];
	const img = new ImageData(w, h);
	const pixels = img.data;
	for (let i = 0; i < data.length; i++) {
		const idx = Math.max(0, Math.min(255, Math.round(data[i] * 255)));
		const lutBase = idx * 3;
		const pxBase = i * 4;
		pixels[pxBase] = lut[lutBase];
		pixels[pxBase + 1] = lut[lutBase + 1];
		pixels[pxBase + 2] = lut[lutBase + 2];
		pixels[pxBase + 3] = 255;
	}
	return img;
}

// ---------------------------------------------------------------------------
// Percentile computation
// ---------------------------------------------------------------------------

/** Compute a percentile value from a Float32Array. p in [0, 100]. */
export function percentile(data: Float32Array, p: number): number {
	const sorted = Float32Array.from(data).sort();
	const idx = Math.min(sorted.length - 1, Math.max(0, Math.floor(sorted.length * p / 100)));
	return sorted[idx];
}

// ---------------------------------------------------------------------------
// All colormap options for UI selects
// ---------------------------------------------------------------------------

export const ALL_COLORMAP_OPTIONS: { value: ColormapName; label: string }[] = [
	{ value: 'blueGreenRed', label: 'Blue-Green-Red' },
	{ value: 'viridis', label: 'Viridis' },
	{ value: 'coolwarm', label: 'Coolwarm' },
	{ value: 'magma', label: 'Magma' },
	{ value: 'inferno', label: 'Inferno' },
	{ value: 'RdBu', label: 'Red-Blue (diverging)' },
	{ value: 'gray', label: 'Grayscale' },
	{ value: 'turbo', label: 'Turbo' },
	{ value: 'cividis', label: 'Cividis (colorblind)' },
];

// ---------------------------------------------------------------------------
// Colorbar drawing
// ---------------------------------------------------------------------------

/**
 * Draw a horizontal color bar with min/max labels onto a Canvas 2D context.
 * Renders at position (x, y) with dimensions (w, h).
 */
export function drawColorbar(
	ctx: CanvasRenderingContext2D,
	x: number,
	y: number,
	w: number,
	h: number,
	colormap: ColormapName,
	min: number,
	max: number,
): void {
	const lut = COLORMAPS[colormap];

	// Draw the gradient bar
	for (let px = 0; px < w; px++) {
		const t = px / (w - 1 || 1);
		const idx = Math.max(0, Math.min(255, Math.round(t * 255)));
		const base = idx * 3;
		ctx.fillStyle = `rgb(${lut[base]},${lut[base + 1]},${lut[base + 2]})`;
		ctx.fillRect(x + px, y, 1, h);
	}

	// Draw border
	ctx.strokeStyle = '#666';
	ctx.lineWidth = 1;
	ctx.strokeRect(x, y, w, h);

	// Draw labels
	ctx.fillStyle = '#ccc';
	ctx.font = '10px monospace';
	ctx.textBaseline = 'top';

	const labelY = y + h + 3;

	ctx.textAlign = 'left';
	ctx.fillText(formatValue(min), x, labelY);

	ctx.textAlign = 'right';
	ctx.fillText(formatValue(max), x + w, labelY);
}
